# Generated by Django 5.0 on 2024-01-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='returngoods',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='returngoods',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase'),
        ),
    ]
