# Generated by Django 5.0 on 2024-01-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_goods_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returngoods',
            old_name='product',
            new_name='purchase',
        ),
    ]
